-- 기준선 스키마: 2026-09-24_130001 운영 스냅샷(db.dump)에서 pg_dump --schema-only 로 추출.
-- 그전까지는 ddl-auto: update 가 스키마를 만들었다. 이미 테이블이 있는 운영/로컬 DB 는
-- baseline-on-migrate 로 이 파일을 실행하지 않고 V1 으로 표시만 하고, 빈 DB 에서만 실행된다.
-- 이후 스키마 변경은 이 파일을 고치지 말고 V2__*.sql 부터 새로 추가한다.
CREATE TABLE public.categories (
    id character varying(255) NOT NULL,
    level character varying(255),
    name character varying(255),
    parent_id character varying(255),
    sort_order integer DEFAULT 0
);

CREATE TABLE public.channel_category_mappings (
    id bigint NOT NULL,
    channel character varying(255) NOT NULL,
    kiosk_main_category character varying(255) NOT NULL,
    kiosk_sub_category character varying(255),
    naver_category_name character varying(255),
    naver_leaf_category_id bigint NOT NULL
);

ALTER TABLE public.channel_category_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_category_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.channel_product_links (
    id bigint NOT NULL,
    channel character varying(255) NOT NULL,
    channel_image_urls text,
    channel_product_no bigint,
    last_error text,
    last_synced_at timestamp(6) without time zone,
    last_synced_name character varying(255),
    last_synced_price integer,
    last_synced_stock integer,
    naver_status character varying(255),
    origin_product_no bigint,
    product_id bigint NOT NULL
);

ALTER TABLE public.channel_product_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_product_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.combinations (
    id_db bigint NOT NULL,
    id character varying(255),
    name character varying(255),
    product_id bigint,
    erp_code character varying(255),
    stock integer,
    sort_order integer,
    deleted boolean DEFAULT false NOT NULL,
    pricea integer,
    priceb integer,
    pricec integer
);

ALTER TABLE public.combinations ALTER COLUMN id_db ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.combinations_id_db_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.customers (
    erp_code character varying(32) NOT NULL,
    danga integer,
    kind character varying(8),
    name character varying(255),
    synced_at timestamp(6) without time zone
);

CREATE TABLE public.erp_order_outbox (
    order_id bigint NOT NULL,
    attempts integer NOT NULL,
    created_at timestamp(6) without time zone,
    last_error character varying(255),
    processed_at timestamp(6) without time zone
);

CREATE TABLE public.option_group_values (
    option_group_id bigint NOT NULL,
    "values" character varying(255),
    sort_order integer NOT NULL
);

CREATE TABLE public.option_groups (
    id bigint NOT NULL,
    name character varying(255),
    product_id bigint,
    sort_order integer
);

ALTER TABLE public.option_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.option_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    final_price integer,
    name character varying(255),
    selected_option character varying(255),
    order_id bigint,
    erp_code character varying(255),
    quantity integer,
    charged_price integer
);

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.orders (
    id bigint NOT NULL,
    customer_name character varying(255),
    status character varying(255),
    "timestamp" timestamp(6) without time zone,
    total_amount integer,
    erp_customer_code character varying(255),
    request_id character varying(64)
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.product_categories (
    product_id bigint NOT NULL,
    main_category character varying(255),
    sub_category character varying(255)
);

CREATE TABLE public.product_hashtags (
    product_id bigint NOT NULL,
    hashtags character varying(255)
);

CREATE TABLE public.product_images (
    product_id bigint NOT NULL,
    image_url character varying(255),
    image_order integer NOT NULL
);

CREATE TABLE public.product_option_images (
    product_id bigint NOT NULL,
    group_name character varying(255),
    image_url text,
    option_value character varying(255)
);

CREATE TABLE public.products (
    id bigint NOT NULL,
    description text,
    detail_category character varying(255),
    is_complex_options boolean,
    name character varying(255) NOT NULL,
    pricec integer NOT NULL,
    erp_code character varying(255),
    is_category_modified boolean DEFAULT false,
    stock integer DEFAULT 0 NOT NULL,
    sort_order character varying(255) DEFAULT 0 NOT NULL,
    gyu character varying(255),
    origin_area_code character varying(255),
    brand_name character varying(255),
    pricea integer,
    priceb integer,
    deleted_at timestamp(6) with time zone,
    deleted_by character varying(100)
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.reco_item_pair (
    id bigint NOT NULL,
    co_count integer NOT NULL,
    score double precision NOT NULL,
    source_erp_code character varying(20) NOT NULL,
    target_erp_code character varying(20) NOT NULL
);

ALTER TABLE public.reco_item_pair ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reco_item_pair_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255),
    role character varying(255),
    username character varying(255)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.channel_category_mappings
    ADD CONSTRAINT channel_category_mappings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.channel_product_links
    ADD CONSTRAINT channel_product_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.combinations
    ADD CONSTRAINT combinations_pkey PRIMARY KEY (id_db);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (erp_code);

ALTER TABLE ONLY public.erp_order_outbox
    ADD CONSTRAINT erp_order_outbox_pkey PRIMARY KEY (order_id);

ALTER TABLE ONLY public.option_groups
    ADD CONSTRAINT option_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reco_item_pair
    ADD CONSTRAINT reco_item_pair_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk2apkms0qt7hv6g289u941adsa UNIQUE (request_id);

ALTER TABLE ONLY public.channel_category_mappings
    ADD CONSTRAINT uk8ryyennnyw1sr4o90ldg5km6v UNIQUE (channel, kiosk_main_category, kiosk_sub_category);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukebyttwarp1x1sdldjjojv75s UNIQUE (erp_code);

ALTER TABLE ONLY public.channel_product_links
    ADD CONSTRAINT ukt1v7njk2sytys35fajiqbvcoj UNIQUE (product_id, channel);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_reco_item_pair_source ON public.reco_item_pair USING btree (source_erp_code);

ALTER TABLE ONLY public.product_option_images
    ADD CONSTRAINT fk5obdd0ix8broucna1ehbq66n FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);

ALTER TABLE ONLY public.option_groups
    ADD CONSTRAINT fkgitc39v93fp481wvy6dkie0rf FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT fklda9rad6s180ha3dl1ncsp8n7 FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.product_hashtags
    ADD CONSTRAINT fko2160xnxw1pb58ciuur7hef90 FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.option_group_values
    ADD CONSTRAINT fkpfqp1uq4n0dryswk2c2niu1wd FOREIGN KEY (option_group_id) REFERENCES public.option_groups(id);

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.combinations
    ADD CONSTRAINT fkr9r7ydsmmbhgutn728c60tk3t FOREIGN KEY (product_id) REFERENCES public.products(id);

