-- 관리자 화면에서 ERP 매입전표(입고)를 기록한 로컬 보조 이력(ErpReceiptLog / ErpReceiptLogLine).
-- 전표 원본은 경영박사 IL<yy> 에 있고, 여기는 취소 가능 여부와 취소 후 상세 조회용이다.
-- Flyway 도입 전 ddl-auto: update 로 이 테이블이 이미 생긴 로컬 DB 가 있어 IF NOT EXISTS 로 만든다.

CREATE TABLE IF NOT EXISTS erp_receipt_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cancelled_at timestamp(6) without time zone,
    cancelled_by character varying(255),
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    erp_date character varying(255),
    il_table character varying(255),
    last_error character varying(500),
    line_count integer,
    memo character varying(255),
    request_id character varying(255) NOT NULL,
    status character varying(255),
    total_amount bigint,
    vendor_code character varying(255),
    vendor_name character varying(255),
    voucher_no integer,
    CONSTRAINT erp_receipt_log_pkey PRIMARY KEY (id),
    CONSTRAINT ukq3vcbx1jggmuwyrigbitao0lr UNIQUE (request_id)
);

CREATE TABLE IF NOT EXISTS erp_receipt_log_line (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ea integer,
    edit_no integer,
    gum bigint,
    item_code character varying(255),
    item_name character varying(255),
    price integer,
    vat bigint,
    log_id bigint,
    CONSTRAINT erp_receipt_log_line_pkey PRIMARY KEY (id),
    CONSTRAINT fkd3gn95f9qqqboj1fcbfgwchl6 FOREIGN KEY (log_id) REFERENCES erp_receipt_log (id)
);

CREATE INDEX IF NOT EXISTS idx_erp_receipt_log_line_log_id ON erp_receipt_log_line (log_id);
